name: nrdbv2

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3434:3434"
    environment:
      PUBLIC_API_URL: https://api-preview.netrunnerdb.com/api/v3/public
    restart: unless-stopped
    volumes:
      - .:/app:delegated
      - /app/node_modules
    stdin_open: true